### ISSUE TITLE
09-06-Probability-Calibration-and-Oversampling-Techniques

### ISSUE THREAD

**Issue by nbup** [solegalli/machine-learning-imbalanced-data#1]
I have a question about calibration on the test dataset.  I see in the notebook CalibratedClassifierCV is fitted on the test data and then predict on the same test data again, would that be overfitting?  In real problem, should CalibratedClassifierCV be used on the test data and predict on another different test data?  

The code I am talking about is as below. 

rf.fit(X_sm, y_sm)

clf_sigmoid = CalibratedClassifierCV(rf, cv=5, method='isotonic')
clf_sigmoid.fit(X_test, y_test)

prob_sigmoid = clf_sigmoid.predict_proba(X_test)[:, 1]

**Comment by solegalli** [comment]
Yes, ideally you would have another hold out sample to better test the calibration.

**Comment by nbup** [comment]
Hi Soledad,

Thanks for answering my question.  I have another question about CalibratedClassifierCV. Based on the sklearn document, there're two ways of using it and I think your model is the third way and I am curious how your CalibratedClassifierCV works.  

Let me illustrate the two ways in sklearn document and lets use your example that I put last time.  First way, if rf is already fitted, cv should be 'prefit' meaning rf would be trained on X_sm, y_sm and calibrated on X_test, y_test.  Second way, if rf is not fitted already, we can use cv=integer number, meaning X_test,y_test would be split to k-folds and then the folds would be trained, calibrated using cross validation. Link below has more detailed explanation and source code. 
https://github.com/scikit-learn/scikit-learn/blob/95119c13a/sklearn/calibration.py#L43

I am confused about how your CalibratedClassifierCV works?  Could you please explain how a fitted rf and cv = integer number work together in CalibratedClassifierCV? 

It seems to me that rf in clf_sigmoid = CalibratedClassifierCV(rf, cv=5, method='isotonic') would be re-trained/overwrite rf.fit(X_sm, y_sm) and thus rf.fit(X_sm, y_sm) is useless.  Am I correct?

Thank you for your time!
